--VIEWING TOP 10 ROWS
select top 10*
from [healthcare_dataset for sql];

--TOTAL NUMBER OF PATIENTS
select COUNT(*) as Total_patients
from [healthcare_dataset for sql];

--AVERAGE AGE OF PATIENTS
SELECT AVG(Age) as Average_age
FROM [healthcare_dataset for sql];

--TOTAL BILLING AMOUNT
SELECT SUM(BILLING_AMOUNT) AS TOTAL_BILLING
FROM [healthcare_dataset for sql];

--AVERAGE BILLING AMOUNT
SELECT AVG(Billing_Amount) AS Average_billing
FROM [healthcare_dataset for sql];

--TOTAL NUMBER OF MALE AND FEMALE PATIENTS
SELECT GENDER, COUNT (*) AS PATIENT_COUNT
FROM [healthcare_dataset for sql]
GROUP BY Gender;

--TOTAL MEDICAL CONDITIONS
SELECT DISTINCT (MEDICAL_CONDITION)
FROM [healthcare_dataset for sql];

--HOW MANY PATIENTS HAD THE VARIOUS MEDICAL CONDITIONS
SELECT MEDICAL_CONDITION, COUNT(*) AS Patient_count
FROM [healthcare_dataset for sql]
GROUP BY Medical_Condition
ORDER BY Patient_count DESC;

--PATIENTS AND THEIR VARIOUS ADMISSION TYpes
SELECT ADMISSION_TYPE, COUNT(*) AS Patient_count
FROM [healthcare_dataset for sql]
GROUP BY Admission_Type
ORDER BY Patient_count DESC;

--COUNT NUMBER OF PATIENTS IN VARIOUS AGE GROUPS
SELECT 
 CASE 
  WHEN AGE BETWEEN 11 AND 20 THEN '11-20'
  WHEN AGE BETWEEN 21 AND 30 THEN '21-30'
  WHEN AGE BETWEEN 31 AND 40 THEN '31-40'
  WHEN AGE BETWEEN 41 AND 50 THEN '41-50'
  WHEN AGE BETWEEN 51 AND 60 THEN '51-60'
  WHEN AGE BETWEEN 61 AND 70 THEN '61-70'
  WHEN AGE >= 71 THEN '71 AND ABOVE'
END AS AGE_GROUP,
COUNT (*) AS PATIENT_COUNT
FROM [healthcare_dataset for sql]
GROUP BY 
 CASE
  WHEN AGE BETWEEN 11 AND 20 THEN '11-20'
  WHEN AGE BETWEEN 21 AND 30 THEN '21-30'
  WHEN AGE BETWEEN 31 AND 40 THEN '31-40'
  WHEN AGE BETWEEN 41 AND 50 THEN '41-50'
  WHEN AGE BETWEEN 51 AND 60 THEN '51-60'
  WHEN AGE BETWEEN 61 AND 70 THEN '61-70'
  WHEN AGE >= 71 THEN '71 AND ABOVE'
END
ORDER BY PATIENT_COUNT DESC;

--WHICH MEDICAL CONDITION HAS HIGHEST NUMBER OF PATIENTS
SELECT TOP 1 
 Medical_Condition,
 COUNT(*) AS TOTAL_PATIENTS
FROM [healthcare_dataset for sql]
GROUP BY Medical_Condition
ORDER BY TOTAL_PATIENTS DESC;

--WHICH MEDICAL CONDITION PRODUCES THE HIGHEST BILLING
SELECT TOP 1 
 Medical_Condition,
 SUM(Billing_Amount) AS TOTAL_BILLING
FROM [healthcare_dataset for sql]
GROUP BY Medical_Condition
ORDER BY TOTAL_BILLING DESC;

--WHAT IS THE AVERAGE BILLING AMOUNT FOR EACH MEDICAL CONDITION
SELECT Medical_Condition,
 AVG(Billing_Amount) AS AVG_BILLING
FROM [healthcare_dataset for sql]
GROUP BY Medical_Condition
ORDER BY AVG_BILLING DESC;

--WHICH INSURANCE PROVIDER HAS THE HIGHEST NUMBER OF PATIENTS
SELECT TOP 1 INSURANCE_PROVIDER, COUNT(*) AS TOTAL_PATIENTS
FROM [healthcare_dataset for sql]
GROUP BY Insurance_Provider
ORDER BY TOTAL_PATIENTS DESC;

--WHAT IS THE AVERAGE LENGTH OF STAY FOR EACH ADMISSION TYPE
SELECT ADMISSION_TYPE, 
 AVG(DATEDIFF(DAY,DATE_OF_ADMISSION,Discharge_Date)) AS AVG_DURATION
FROM [healthcare_dataset for sql]
GROUP BY Admission_Type
ORDER BY AVG_DURATION;

--WHICH DRUG IS MOST PRESCRIBED
SELECT TOP 1 MEDICATION, 
COUNT (*) AS FREQUENCY
FROM [healthcare_dataset for sql]
GROUP BY Medication
ORDER BY FREQUENCY;

--HOW MANY PATIENTS HAD EACH TEST RESULT
SELECT TEST_RESULTS,
COUNT (*) AS PATIENT_COUNT
FROM [healthcare_dataset for sql]
GROUP BY Test_Results
ORDER BY PATIENT_COUNT DESC;

--WHICH AGE GROUP HAS THE HIGHEST AVERAGE BILLING
SELECT TOP 1
 CASE 
  WHEN AGE BETWEEN 11 AND 20 THEN '11-20'
  WHEN AGE BETWEEN 21 AND 30 THEN '21-30'
  WHEN AGE BETWEEN 31 AND 40 THEN '31-40'
  WHEN AGE BETWEEN 41 AND 50 THEN '41-50'
  WHEN AGE BETWEEN 51 AND 60 THEN '51-60'
  WHEN AGE BETWEEN 61 AND 70 THEN '61-70'
  WHEN AGE >= 71 THEN '71 AND ABOVE'
END AS AGE_GROUP,
AVG(BILLING_AMOUNT) AS BILLING_AMNT
FROM [healthcare_dataset for sql]
GROUP BY 
 CASE
  WHEN AGE BETWEEN 11 AND 20 THEN '11-20'
  WHEN AGE BETWEEN 21 AND 30 THEN '21-30'
  WHEN AGE BETWEEN 31 AND 40 THEN '31-40'
  WHEN AGE BETWEEN 41 AND 50 THEN '41-50'
  WHEN AGE BETWEEN 51 AND 60 THEN '51-60'
  WHEN AGE BETWEEN 61 AND 70 THEN '61-70'
  WHEN AGE >= 71 THEN '71 AND ABOVE'
END
ORDER BY BILLING_AMNT DESC;

--TOP 10 HOSPITALS BY TOTAL BILLING
SELECT TOP 10 HOSPITAL,
SUM(BILLING_AMOUNT) AS TOTAL_BILLING
FROM [healthcare_dataset for sql]
GROUP BY Hospital
ORDER BY TOTAL_BILLING DESC;

--WHICH MEDICAL CONDITION HAD THE LONGEST AVERAGE LENGTH OF STAY
SELECT TOP 1 MEDICAL_CONDITION,
AVG(DATEDIFF(DAY,DATE_OF_ADMISSION,Discharge_Date)) AS AVG_DURATION
FROM [healthcare_dataset for sql]
GROUP BY MEDICAL_CONDITION
ORDER BY AVG_DURATION DESC;

--WHICH COMBINATION OF MEDICAL CONDITIONS AND ADMISSION TYPE HAS THE HIGHEST PATIENT COUNT?
SELECT MEDICAL_CONDITION, ADMISSION_TYPE,
COUNT (*) AS PATIENT_COUNT
FROM [healthcare_dataset for sql]
GROUP BY MEDICAL_CONDITION, ADMISSION_TYPE
ORDER BY PATIENT_COUNT;
